SuperHero.UI/Controllers/CharactersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SuperHero.DATA.EF;

namespace SuperHero.UI.Controllers
{

    public class CharactersController : Controller
    {
        private SuperHeroEntities db = new SuperHeroEntities();

        // GET: Characters
        [Authorize]
        public ActionResult Index()
        {
            return View(db.Characters.ToList());
        }

        // GET: Characters/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Character character = db.Characters.Find(id);
            if (character == null)
            {
                return HttpNotFound();
            }
            return View(character);
        }

        // GET: Characters/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Characters/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "CharacterID,Name,Alias,Description,Occupation,IsHero,IsActive")] Character character, HttpPostedFileBase heroImage)
        {
            //HttpPostedFileBase is the datatype for the file.  The name of the variable MUST match the name attribute of the input type=file in the UI 
            if (ModelState.IsValid)
            {
                //establish a variable for our default image
                string imageName = "noImage.png";
                //if a file was sent
                if (heroImage != null)
                {
                    //reassign the variable to the filename that was sent over
                    imageName = heroImage.FileName;

                    //create a variable for the extension
                    string ext = imageName.Substring(imageName.LastIndexOf('.'));

                    //create a list of valid extensions
                    string[] goodExts = { ".jpeg", ".jpg", ".png", ".gif" };

                    //if the file extension is valid, assign a GUID as the name and concatenate the extension
                    //string guid = new Guid().ToString();

                    if (goodExts.Contains(ext.ToLower()))
                    {
                        //imageName = guid + ext;
                        //save the file to the webserver
                        heroImage.SaveAs(Server.MapPath("~/Content/Images/Heroes/" + imageName));
                    }
                    else
                    {
                        imageName = "noImage.png";
                    }                    
                }
                character.CharacterImage = imageName;
                db.Characters.Add(character);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(character);
        }

        // GET: Characters/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Character character = db.Characters.Find(id);
            if (character == null)
            {
                return HttpNotFound();
            }
            return View(character);
        }

        // POST: Characters/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "CharacterID,Name,Alias,Description,Occupation,IsHero,IsActive")] Character character, HttpPostedFileBase heroImage)
        {
            //HttpPostedFileBase is the datatype for the file.  The name of the variable MUST match the name attribute of the input type=file in the UI 
            if (ModelState.IsValid)
            {
                //establish a variable for our default image
                string imageName = "noImage.png";
                //if a file was sent
                if (heroImage != null)
                {
                    //reassign the variable to the filename that was sent over
                    imageName = heroImage.FileName;

                    //create a variable for the extension
                    string ext = imageName.Substring(imageName.LastIndexOf('.'));

                    //create a list of valid extensions
                    string[] goodExts = { ".jpeg", ".jpg", ".png", ".gif" };

                    //if the file extension is valid, assign a GUID as the name and concatenate the extension
                    //string guid = new Guid().ToString();

                    if (goodExts.Contains(ext.ToLower()))
                    {
                        //imageName = guid + ext;
                        //save the file to the webserver
                        heroImage.SaveAs(Server.MapPath("~/Content/Images/Heroes/" + imageName));
                    }
                    else
                    {
                        imageName = "noImage.png";
                    }
                }
                character.CharacterImage = imageName;
                db.Entry(character).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(character);
        }
        // POST: Characters/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Character character = db.Characters.Find(id);
            db.Characters.Remove(character);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SuperHero.UI/Controllers/CoursController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SuperHero.DATA.EF;

namespace SuperHero.UI.Controllers
{
    
    public class CoursController : Controller
    {
        private SuperHeroEntities db = new SuperHeroEntities();

        // GET: Cours
        [Authorize]
        public ActionResult Index()
        {
            var courses = db.Courses.Include(c => c.CourseType).Include(c => c.Location);
            return View(courses.ToList());
        }

        // GET: Cours/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cours cours = db.Courses.Find(id);
            if (cours == null)
            {
                return HttpNotFound();
            }
            return View(cours);
        }

        // GET: Cours/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.CourseTypeID = new SelectList(db.CourseTypes, "CourseTypeID", "Name");
            ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "Address");
            return View();
        }

        // POST: Cours/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "CourseID,Name,Description,CourseTypeID,Date,LocationID")] Cours cours)
        {
            if (ModelState.IsValid)
            {
                db.Courses.Add(cours);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CourseTypeID = new SelectList(db.CourseTypes, "CourseTypeID", "Name", cours.CourseTypeID);
            ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "Address", cours.LocationID);
            return View(cours);
        }

        // GET: Cours/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cours cours = db.Courses.Find(id);
            if (cours == null)
            {
                return HttpNotFound();
            }
            ViewBag.CourseTypeID = new SelectList(db.CourseTypes, "CourseTypeID", "Name", cours.CourseTypeID);
            ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "Address", cours.LocationID);
            return View(cours);
        }

        // POST: Cours/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "CourseID,Name,Description,CourseTypeID,Date,LocationID")] Cours cours)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cours).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CourseTypeID = new SelectList(db.CourseTypes, "CourseTypeID", "Name", cours.CourseTypeID);
            ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "Address", cours.LocationID);
            return View(cours);
        }

        // GET: Cours/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cours cours = db.Courses.Find(id);
            if (cours == null)
            {
                return HttpNotFound();
            }
            return View(cours);
        }

        // POST: Cours/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Cours cours = db.Courses.Find(id);
            db.Courses.Remove(cours);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SuperHero.UI/Controllers/LocationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SuperHero.DATA.EF;

namespace SuperHero.UI.Controllers
{
    
    public class LocationsController : Controller
    {
        private SuperHeroEntities db = new SuperHeroEntities();

        // GET: Locations
        [Authorize]
        public ActionResult Index()
        {
            return View(db.Locations.ToList());
        }

        // GET: Locations/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location = db.Locations.Find(id);
            if (location == null)
            {
                return HttpNotFound();
            }
            return View(location);
        }

        // GET: Locations/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Locations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "LocationID,Address,City,State,Planet")] Location location)
        {
            if (ModelState.IsValid)
            {
                db.Locations.Add(location);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(location);
        }

        // GET: Locations/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location = db.Locations.Find(id);
            if (location == null)
            {
                return HttpNotFound();
            }
            return View(location);
        }

        // POST: Locations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "LocationID,Address,City,State,Planet")] Location location)
        {
            if (ModelState.IsValid)
            {
                db.Entry(location).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(location);
        }

        // GET: Locations/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location = db.Locations.Find(id);
            if (location == null)
            {
                return HttpNotFound();
            }
            return View(location);
        }

        // POST: Locations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Location location = db.Locations.Find(id);
            db.Locations.Remove(location);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SuperHero.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords" content="Super Heroes Inc., superheroes, citizen safety, drop crime rates, villains" />
    <title>@ViewBag.Title</title>

    <link href='http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500italic,500,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
    <!-- Bootstrap -->
    <link href="~/content/css/bootstrap.min.css" rel="stylesheet">
    <!-- FontAwesome -->
    <link rel="stylesheet" href="~/content/css/font-awesome.min.css">
    <!-- MaterialCSS -->
    <link rel="stylesheet" href="~/content/css/material.min.css">
    <!-- RipplesCSS -->
    <link rel="stylesheet" href="~/content/css/ripples.min.css">

    <!-- ThemeCSS & Responsive CSS -->
    <link rel="stylesheet" href="~/content/style.css">
    <link rel="stylesheet" href="~/content/css/responsive.css">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    @RenderSection("styles", false)
    <link href="~/Content/css/custom.css" rel="stylesheet" />
</head>
<body>

    <header class="header">
        <div data-velocity="-.4" id="particles" class="header-bg"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="social-links">
                        <a class="btn social-link" href="javascript:void(0)"><i class="fa fa-facebook"></i> <div class="ripple-wrapper"></div></a>
                        <a class="btn social-link" href="javascript:void(0)"><i class="fa fa-twitter"></i> <div class="ripple-wrapper"></div></a>
                        <a class="btn social-link" href="javascript:void(0)"><i class="fa fa-instagram"></i> <div class="ripple-wrapper"></div></a>
                    </div>
                </div>
            </div>
        </div>

        <div class="site-title-table">
            <div class="site-title-tablecell">
                <div class="slide-text">
                    <h2><a href="@Url.Action("Index", "Home")"><span>S</span>uper<span>H</span>eros, <span>I</span>nc.</a></h2>
                    <p>Promoting Citizen Safety through Education</p>
                </div>
            </div>
        </div>
    </header>

    <section class="maincontent-wrap">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="maincotnent shadow-z-1">
                        <div class="mainmenu">
                            <div class="navbar navbar-nobg">
                                <div class="navbar-header">
                                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                        <span class="sr-only">Toggle navigation</span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                    </button>
                                </div>
                                <div class="navbar-collapse collapse">
                                    <ul id="mainnav" class="nav navbar-nav">
                                        <li class="navli"><a href="@Url.Action("Index", "Home")">Our Mission <div class="ripple-wrapper"></div></a></li>
                                        <li class="navli"><a href="@Url.Action("Calendar", "Home")">Calendar</a></li>
                                        <li class="navli"><a href="@Url.Action("Contact", "Home")">Contact</a></li>
                                        @if (Request.IsAuthenticated)
                                        {
                                            <li class="navli"><a href="@Url.Action("Index", "Characters")">All Heroes</a></li>
                                            <li class="navli"><a href="@Url.Action("Index", "Cours")">All Courses</a></li>
                                            <li class="navli"><a href="@Url.Action("Index", "CourseTypes")">Course Types</a></li>
                                            <li class="navli"><a href="@Url.Action("Index", "Locations")">Course Locations</a></li>
                                            if (User.IsInRole("Admin"))
                                            {
                                                <li class="navli"><a href="@Url.Action("Index", "CourseCharacters")">Assign Instructors</a></li>
                                            }
                                        }
                                        @Html.Partial("_LoginPartial")
                                    </ul>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-10 col-md-offset-1">
                                <div class="article-list">

                                    @RenderBody()


                                </div>
                            </div>
                        </div>


                    </div>
                </div>
            </div>
        </div>
    </section>

    <footer class="footer">
        <div class="container">


            <div class="row">
                <div class="col-md-12">
                    <div class="footer-bottom">
                        <div class="row">
                            <div class="col-md-8">
                                <div class="copyright-text">
                                    <p>© 2015 Avengers - All Rights Reserved. Coded with <i class="fa fa-heart"></i> by <a href="http://wpexpand.com" target="_blank">WP Expand</a></p>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="social-links footer-social-links">
                                    <a class="btn social-link" href="javascript:void(0)"><i class="fa fa-facebook"></i> <div class="ripple-wrapper"></div></a>
                                    <a class="btn social-link" href="javascript:void(0)"><i class="fa fa-twitter"></i> <div class="ripple-wrapper"></div></a>
                                    <a class="btn social-link" href="javascript:void(0)"><i class="fa fa-instagram"></i> <div class="ripple-wrapper"></div></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>


    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="~/content/js/vendor/jquery-1.11.2.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="~/content/js/bootstrap.min.js"></script>
    <script src="~/content/js/material.min.js"></script>
    <script src="~/content/js/ripples.min.js"></script>
    <script src="~/content/js/jquery.scrolly.js"></script>
    <script src="~/content/js/jquery.particleground.min.js"></script>
    <script src="~/content/js/main.js"></script>
    @RenderSection("scripts", false)
</body>
</html>

SuperHero.UI/Views/Shared/_OriginalLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>

                    @if (Request.IsAuthenticated && User.IsInRole("Admin")) {
                        <li>@Html.ActionLink("RolesAdmin", "Index", "RolesAdmin")</li>
                        <li>@Html.ActionLink("UsersAdmin", "Index", "UsersAdmin")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>